AuctionsWeb/Controllers/AdminFunctionalitiesController.cs
using AuctionsWeb.Models;
using System.Linq;
using System.Web.Mvc;
using AuctionsWeb.Enums;
using System.Collections.Generic;
using System;

namespace AuctionsWeb.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminFunctionalitiesController : Controller
    {
        [HttpGet]
        public ActionResult OpenAuctions(OpenAuctionsModel model)
        {
            model = new OpenAuctionsModel();
            auctiondbEntities entities = new auctiondbEntities();
            model.auctions = entities.Auctions.Where(x => x.State.Equals("READY")).ToList();
            return View(model);
        }

        public ActionResult Add(int id)
        {
            auctiondbEntities db = new auctiondbEntities();
            var auction = db.Auctions.First(a => a.Id == id);
            auction.State = AuctionStates.OPEN.ToString();
            auction.TimeOpen = DateTime.Now;
            auction.TimeEnd = DateTime.Now.AddSeconds((int)auction.Duration);
            db.SaveChanges();

            return RedirectToAction("OpenAuctions");
        }

        public ActionResult ApproveTokens()
        {
            var model = new ApproveTokensModel();
            auctiondbEntities db = new auctiondbEntities();
            List<Order> orders = db.Orders.Where(o => o.State == OrderStates.SUBMITTED.ToString()).ToList();
            model.orders = orders;
            return View(model);

        }

        public ActionResult Approve(int id)
        {
            auctiondbEntities db = new auctiondbEntities();
            var order = db.Orders.First(o => o.Id == id);
            order.State = OrderStates.COMPLETED.ToString();
            order.AspNetUser.NumTokens += order.NumTokens;
            db.SaveChanges();
            return RedirectToAction("ApproveTokens");

        }

        public ActionResult Cancel(int id)
        {
            auctiondbEntities db = new auctiondbEntities();
            var order = db.Orders.First(o => o.Id == id);
            order.State = OrderStates.CANCELED.ToString();
            db.SaveChanges();
            return RedirectToAction("ApproveTokens");
        }

        public ActionResult ControlPanel()
        {
            var model = new ControlPanelModel();
            return View(model);
        }
    }
}

AuctionsWeb/Controllers/UserFunctionalitiesController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AuctionsWeb.Models;
using Microsoft.AspNet.Identity;
using AuctionsWeb.Enums;
using System.Collections.Generic;
using AuctionsWeb.Constants;

namespace AuctionsWeb.Controllers
{
    [Authorize]
    public class UserFunctionalitiesController : Controller
    {
        // GET: UserFunctionalities
        public ActionResult CreateAuction()
        {
            ViewBag.Message = "Create Auction page.";
            var model = new CreateAuctionModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreateAuction(CreateAuctionModel model)
        {
            if (ModelState.IsValid)
            {
                var auction = new Auction {
                    IdUser = User.Identity.GetUserId(),
                    Name = model.AuctionName,
                    Duration = (model.Duration == 0) ? SystemParameters.DEFAULT_AUCTION_DURATION : model.Duration,
                    Photo = model.PhotoURL,
                    PriceStart = model.PriceStart,
                    PriceNow = model.PriceStart,
                    State = "READY",
                    TimeCreate = System.DateTime.Now,
                    TotalTokens = 0
                };

                var entity = new auctiondbEntities();
                entity.Auctions.Add(auction);
                await entity.SaveChangesAsync();
                return Redirect("/");
            } 
            return View();
        }

        
        public ActionResult ShopTokens()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ShopTokens(ShopTokensModel model)
        {
            if (model.NumTokens == 0)
            {
                ViewBag.ErrorMessage = "Choose one of three token packages";
                return View();
            }
            TempData["ShopTokenInfo"] = new ShopTokensModel(model.Currency, model.NumTokens);
            return Redirect("PurchaseTokens");
        }

        public ActionResult PurchaseTokens()
        {
            var db = new auctiondbEntities();
            var user = db.AspNetUsers.Find(User.Identity.GetUserId());
            ShopTokensModel shopTokenInfo = TempData["ShopTokenInfo"] as ShopTokensModel;
            PurchaseTokensModel model = new PurchaseTokensModel()
            {
                Currency = shopTokenInfo.Currency,
                NumTokens = shopTokenInfo.NumTokens,
                FirstName = user.FirstName,
                LastName = user.LastName,
                TotalPrice = shopTokenInfo.NumTokens * AuctionsWeb.Constants.SystemParameters.TOKEN_VALUE
            };
            TempData["PurchaseTokensModel"] = model;

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> PurchaseTokens(PurchaseTokensModel modele)
        {
            var db = new auctiondbEntities();
            var user = db.AspNetUsers.Find(User.Identity.GetUserId());
            PurchaseTokensModel model = TempData["PurchaseTokensModel"] as PurchaseTokensModel;
            var order = new Order()
            {
                IdUser = User.Identity.GetUserId(),
                NumTokens = model.NumTokens,
                Price = model.TotalPrice,
                State = OrderStates.SUBMITTED.ToString()
            };
            db.Orders.Add(order);
            await db.SaveChangesAsync();
            return Redirect("/");
        }

        public ActionResult Orders()
        {
            var db = new auctiondbEntities();
            var id = User.Identity.GetUserId();
            var user = db.AspNetUsers.First(u => u.Id == id);
            var orders = user.Orders;
            return View(orders);
        }

        public ActionResult WonAuctions()
        {
            var model = new WonAuctionsModel();
            model.auctions = new List<Auction>();
            var db = new auctiondbEntities();
            var userId = User.Identity.GetUserId();
            var auctions = db.Auctions;
            foreach (var auction in auctions)
            {
                if (auction.Winner == userId)
                {
                    model.auctions.Add(auction);
                }
            }
            return View(model);
        }

        public ActionResult AuctionDetails(int idAuction)
        {

            return Redirect("~/Home/Auction/" + idAuction);
        }
    }
}

AuctionsWeb/Views/Shared/AuctionTable.cshtml
@model ICollection<Bid>    

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Auction Name</th>
            <th scope="col">UserName</th>
            <th scope="col">Time of Bid</th>
            <th scope="col">Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bid in Model)
        {
            <tr>
                <td>@bid.Auction.Name</td>
                <td>@bid.AspNetUser.UserName</td>
                <td>@bid.Time</td>
                <td>@bid.Amount</td>
            </tr>
        }
    </tbody>
</table>

AuctionsWeb/Views/Shared/BidModal.cshtml
@model AuctionsWeb.Models.BidModalModel


    <div class="modal-header">
        <h5 class="modal-title">Add your bid</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @using (Html.BeginForm("CreateBid", "Home", Model , FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.BidAmount, htmlAttributes: new { @class = "col-form-label" })
                    @Html.TextBoxFor(model => model.BidAmount, new { @Value = 1 })
                </div>
                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
    }

AuctionsWeb/Views/Shared/Card.cshtml
@model Auction

@{
    var lastBidder = "No Bids Yet";
    var bids = Model.Bids.AsQueryable();
    bids = bids.OrderByDescending(a => a.Time);
    if (!bids.Count().Equals(0))
    {
        lastBidder = bids.First().AspNetUser.UserName;
    }
}

<div class="col">
    <div class="card">
        <div class="card-header bg-transparent border-success">
            @Html.ActionLink(Model.Name, "Auction", "Home", new { id = Model.Id }, null)
        </div>
        <img class="card-img-top" src="http://via.placeholder.com/277x200" alt="Card image cap">
        <div class="card-body">
            <p class="card-text">@Model.PriceNow</p>
            <p class="card-text">@lastBidder</p>
            <h5 class="card-title">@Model.State</h5>
        </div>
        <div class="card-footer">
            <small class="text-muted">@DateTime.Now.ToShortTimeString()</small>
        </div>
    </div>
</div>

AuctionsWeb/Views/Shared/Cards.cshtml
@model List<Auction>

@{ 
    var djoka = 0;
}
<div class="card-deck">
    @foreach (var auction in Model)
    {
        var lastBidder = "No Bids Yet";
        var bids = auction.Bids;

        if (!bids.Count().Equals(0))
        {
            lastBidder = bids.OrderByDescending(a => a.Time).First().AspNetUser.UserName;
        }

        <div class="col-sm-3 mt-4">
            <div class="card">
                <div class="card-header bg-transparent border-success">
                    @Html.ActionLink(auction.Name, "Auction", "Home", new { Id = auction.Id }, null)
                </div>
                <img class="card-img-top" src="http://via.placeholder.com/277x200" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">@auction.PriceNow</p>
                    <p class="card-text">@lastBidder</p>
                    <h5 class="card-title">@auction.State</h5>

                    @{
                        TimeSpan timeLeft = TimeSpan.Zero;
                        if (auction.State.Contains("OPEN"))
                        {
                            var tl = auction.TimeEnd - DateTime.Now;
                            timeLeft = (TimeSpan)tl;
                        }
                        else if (auction.State.Contains("READY"))
                        {
                            timeLeft = TimeSpan.FromSeconds((long)auction.Duration);
                        }
                    }


                    @if (auction.State.Contains("OPEN"))
                    {
                        <button id="btnSubmit" class="btn btn-primary btn-sm" data-target="#myModal" data-toggle="modal" onclick="
                                $.ajax({
                                    url: '/Home/ModalAction',
                                    data: { auctionId: @auction.Id }
                                });"
                        >
                            Bid
                        </button>
                    }
                    else
                    {
                        <button id = "btnSubmit" class="btn btn-primary btn-sm disabled" data-target="#myModal" data-toggle="modal" disabled>Bid</button>
                    }

                </div>
                <div class="card-footer">
                    <h5>@timeLeft.ToString("hh\\:mm\\:ss")</h5>
                </div>
            </div>
        </div>


        


        }
</div>

AuctionsWeb/Views/Shared/ModalContent.cshtml
@model AuctionsWeb.Models.BidModalModel

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p>User id : @Model.UserId </ p >
        <p>Auction id : @Model.AuctionId </ p >


        @using (Html.BeginForm("ModalAction", "Home", Model , FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.NewBid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.NewBid, new { @Value = Model.LastBid })
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary">Submit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    </div>
</div>

AuctionsWeb/Views/Shared/Timer.cshtml
@model Auction

@{
    var remaining = Model.TimeEnd - DateTime.Now;
}
<h5>@remaining</h5>

AuctionsWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">AuctionsWeb</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    
                    <li>
                        <div class="nav-link">
                            @Html.ActionLink("Search", "Search", "Home")
                        </div>
                    </li>

                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("admin"))
                        {
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("OpenAuctions", "OpenAuctions", "AdminFunctionalities")
                                </div>
                            </li>
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("ApproveTokens", "ApproveTokens", "AdminFunctionalities")
                                </div>
                            </li>
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("ControlPanel", "ControlPanel", "AdminFunctionalities")
                                </div>
                            </li>
                        }
                        else
                        {
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("CreateAuction", "CreateAuction", "UserFunctionalities")
                                </div>
                            </li>
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("ShopTokens", "ShopTokens", "UserFunctionalities")
                                </div>
                            </li>
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("Orders", "Orders", "UserFunctionalities")
                                </div>
                            </li>
                            <li>
                                <div class="nav-link">
                                    @Html.ActionLink("WonAuctions", "WonAuctions", "UserFunctionalities")
                                </div>
                            </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")


            </div>
        </nav>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>                                                                                                                                                                                                                                          